# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4  # Ruff version
    hooks:
      # Run the linter
      - id: ruff-check
      # Run the formatter
      - id: ruff-format
