# https://docs.astral.sh/ruff/formatter/#configuration
# https://docs.astral.sh/ruff/settings
[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
