version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise:10.1.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml

  prometheus:
    image: prom/prometheus:v2.46.0
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  grafana-storage: {}
  prometheus-storage: {}
